### ISSUE TITLE
Cool but are there more instructions?

### ISSUE THREAD

**Issue by ghost** [AnthonyKNorman/ESP8266-RF_Sniffer#1]
This is a pretty cool project, I must say! I have an esp8266 myself and its been a while since i have used it so i plan to use it for this. But can you please add more instructions as it is not clear what to do with this. I mean, obviously I guess im supposed to flash the ino file to my arduino and judging from the source code, I'm supposed to use the serial terminal to control it, correct? Anyways, if im wrong, i would appreciate an update to give clearer instructions. Thanks you.

**Comment by AnthonyKNorman** [comment]
Yes, using the Arduino IDE, you flash the file to your ESP8266. You can use the serial connection, but it was designed to work without.
Each time it detects a signal, that will show up n the screen. A short press on the button will scroll through the signals received. A long press will erase the records.
